### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by dreadnip** [sumocoders/application-skeleton#10]
This is a list of components that almost any of our framework projects will use but are not present in the skeleton composer.json as of today:

- [ ] symfony/form
- [ ] symfony/messenger
- [ ] symfony/validator
- [ ] annotations
- [ ] symfony/mailer
- [x] symfony/dotenv *
- [x] symfony/monolog-bundle *
- [x] symfony/yaml *

\* are required to deploy to staging

**Comment by tijsverkoyen** [comment]
symfony/dotenv, symfony/monolog-bundle and symfony/yaml are fixed in symfony/yaml
