### ISSUE TITLE
SensioLabs Security Checker Discontinued

### ISSUE THREAD

**Issue by stefnielandt** [sumocoders/application-skeleton#17]
https://github.com/sumocoders/application-skeleton/blob/063f419fb44f140e9e938045c71a0a57efb19441/composer.json#L29

Excerpt from [SensioLabs Security Checker](https://github.com/sensiolabs/security-checker):
WARNING: Don't use this piece of software anymore as the underlying web service will stop working at the end of January 2021. Instead, use the Open-Source CLI tool that does the same locally, or use the Symfony CLI tool.

Including it will add a script to composer auto-scripts that will break any and all composer commands in dev env.

**Comment by tijsverkoyen** [comment]
Is fixed in https://github.com/sumocoders/application-skeleton/pull/18
